readinessProbe:
  exec:
    command:
      - sh
      - -c
      - "pgrep -f 'python.*main.py' || exit 1"
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 3
runAsUser: 101
runAsGroup: 101
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 8
customEnv:
  - name: DOWNLOAD_DIR
    value: "data/"
  - name: ALLOWED_USERS
    value: "4444"
  - name: TG_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: bot-token-super-easy-test
        key: token
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: openai-api-key
        key: token
  - name: TG_API_ADMIN_BOT_TOKEN
    valueFrom:
      secretKeyRef:
        name: bot-token-admin
        key: token
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
          name: admin
          key: name
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
          name: admin
          key: password
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
          name: admin
          key: host
  - name: DB_PORT
    valueFrom:
      secretKeyRef:
          name: admin
          key: port
  - name: LIFE_CS_CHAT_ID
    valueFrom:
      secretKeyRef:
        name: life-chat-id
        key: token
  - name: ADMIN_CHAT_ID
    valueFrom:
      secretKeyRef:
        name: admin-chat-id
        key: token
resources:
   requests:
     cpu: 200m
     memory: 1024Mi
   limits:
     cpu: 400m
     memory: 2048Mi